name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils:
    git:
      url: https://github.com/kahero-team/esc_pos_utils.git
  escposprinter:
    git: https://github.com/kahero-team/esc-pos-printer-flutter.git
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
